"""add image_url to all tables

Revision ID: 23502fb11680
Revises: 703f9f3eaed2
Create Date: 2026-05-02 00:02:39.286729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23502fb11680'
down_revision: Union[str, Sequence[str], None] = '703f9f3eaed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('messier_objects', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('planets', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('stars', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stars', 'image_url')
    op.drop_column('planets', 'image_url')
    op.drop_column('messier_objects', 'image_url')
    op.drop_column('agencies', 'image_url')
    # ### end Alembic commands ###
