"""create planets tables

Revision ID: 378430167a6b
Revises: 
Create Date: 2026-04-19 18:07:45.354038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378430167a6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('fun_facts', sa.JSON(), nullable=True))
    op.add_column('planets', sa.Column('african_context', sa.Text(), nullable=True))
    op.add_column('planets', sa.Column('visible_from_nigeria', sa.Boolean(), nullable=True))
    op.add_column('planets', sa.Column('naked_eye', sa.Boolean(), nullable=True))
    op.add_column('planets', sa.Column('viewing_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'viewing_notes')
    op.drop_column('planets', 'naked_eye')
    op.drop_column('planets', 'visible_from_nigeria')
    op.drop_column('planets', 'african_context')
    op.drop_column('planets', 'fun_facts')
    # ### end Alembic commands ###
