"""add messier_objects fields

Revision ID: 386a6dfa8983
Revises: 9746e4a0d40c
Create Date: 2026-04-26 15:28:47.010056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386a6dfa8983'
down_revision: Union[str, Sequence[str], None] = '9746e4a0d40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messier_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('messier_number', sa.Integer(), nullable=True),
    sa.Column('ngc_number', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('constellation', sa.String(), nullable=True),
    sa.Column('distance_light_years', sa.Float(), nullable=True),
    sa.Column('apparent_magnitude', sa.Float(), nullable=True),
    sa.Column('right_ascension', sa.String(), nullable=True),
    sa.Column('declination', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fun_facts', sa.String(), nullable=True),
    sa.Column('african_context', sa.String(), nullable=True),
    sa.Column('discovery_year', sa.Integer(), nullable=True),
    sa.Column('discovered_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messier_objects_id'), 'messier_objects', ['id'], unique=False)
    op.create_index(op.f('ix_messier_objects_name'), 'messier_objects', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messier_objects_name'), table_name='messier_objects')
    op.drop_index(op.f('ix_messier_objects_id'), table_name='messier_objects')
    op.drop_table('messier_objects')
    # ### end Alembic commands ###
