"""add new planet fields

Revision ID: 5aad3b8c3d5f
Revises: bf66c9a8116e
Create Date: 2026-04-20 20:27:03.043609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aad3b8c3d5f'
down_revision: Union[str, Sequence[str], None] = 'bf66c9a8116e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
