"""add astronauts table

Revision ID: 5ebfbffcbef2
Revises: a3e48a6d4978
Create Date: 2026-05-16 18:35:48.899196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebfbffcbef2'
down_revision: Union[str, Sequence[str], None] = 'a3e48a6d4978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_astronaults_id'), table_name='astronaults')
    op.drop_table('astronaults')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astronaults',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_biography', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('missions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_historical', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('astronaults_pkey')),
    sa.UniqueConstraint('name', name=op.f('astronaults_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_astronaults_id'), 'astronaults', ['id'], unique=False)
    # ### end Alembic commands ###
