"""add stars table

Revision ID: 601d9aa6b50f
Revises: b41adafe8fa3
Create Date: 2026-04-23 00:41:16.106230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601d9aa6b50f'
down_revision: Union[str, Sequence[str], None] = 'b41adafe8fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stars', 'designation')
    # ### end Alembic commands ###
