"""add new planet fields

Revision ID: 6890296fa8e0
Revises: 0431730c0633
Create Date: 2026-04-20 17:56:01.735456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6890296fa8e0'
down_revision: Union[str, Sequence[str], None] = '0431730c0633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('naked_eye_view', sa.Boolean(), nullable=True))
    op.alter_column('planets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('planets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('planets', 'naked_eye')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('naked_eye', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('planets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('planets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('planets', 'naked_eye_view')
    # ### end Alembic commands ###
