"""add planets fields

Revision ID: 94e09a0c0bd5
Revises: 378430167a6b
Create Date: 2026-04-20 09:39:38.840714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94e09a0c0bd5'
down_revision: Union[str, Sequence[str], None] = '378430167a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('surface_gravity', sa.Float(), nullable=True))
    op.add_column('planets', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('planets', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('planets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('planets', 'fun_facts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('planets', 'african_context')
    op.drop_column('planets', 'viewing_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('viewing_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('african_context', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('planets', 'fun_facts',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('planets', 'updated_at')
    op.drop_column('planets', 'created_at')
    op.drop_column('planets', 'temperature')
    op.drop_column('planets', 'surface_gravity')
    # ### end Alembic commands ###
