"""add astronaults table

Revision ID: a3e48a6d4978
Revises: bf98e4a11ebb
Create Date: 2026-05-16 15:01:23.591139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e48a6d4978'
down_revision: Union[str, Sequence[str], None] = 'bf98e4a11ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astronaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('short_biography', sa.String(), nullable=True),
    sa.Column('long_biography', sa.Text(), nullable=True),
    sa.Column('missions', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('is_historical', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_astronaults_id'), 'astronaults', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_astronaults_id'), table_name='astronaults')
    op.drop_table('astronaults')
    # ### end Alembic commands ###
