"""add long and short descriptions

Revision ID: a5eabe9dd2a0
Revises: 5ebfbffcbef2
Create Date: 2026-05-17 17:50:23.382852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5eabe9dd2a0'
down_revision: Union[str, Sequence[str], None] = '5ebfbffcbef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('stars', sa.Column('long_description', sa.Text(), nullable=True))
    op.alter_column('stars', 'african_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('stars', 'traditional_uses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('stars', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('stars', 'traditional_uses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('stars', 'african_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('stars', 'long_description')
    op.drop_column('stars', 'short_description')
    # ### end Alembic commands ###
