"""add exoplanets column

Revision ID: b13175f9036c
Revises: 7bf909b6d1e0
Create Date: 2026-05-09 08:18:34.487728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13175f9036c'
down_revision: Union[str, Sequence[str], None] = '7bf909b6d1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('is_exoplanet', sa.Boolean(), nullable=True))
    op.add_column('planets', sa.Column('host_star', sa.String(), nullable=True))
    op.add_column('planets', sa.Column('discovery_method', sa.String(), nullable=True))
    op.add_column('planets', sa.Column('discovery_year', sa.Integer(), nullable=True))
    op.add_column('planets', sa.Column('distance_from_earth_ly', sa.Float(), nullable=True))
    op.add_column('planets', sa.Column('african_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'african_context')
    op.drop_column('planets', 'distance_from_earth_ly')
    op.drop_column('planets', 'discovery_year')
    op.drop_column('planets', 'discovery_method')
    op.drop_column('planets', 'host_star')
    op.drop_column('planets', 'is_exoplanet')
    # ### end Alembic commands ###
