"""add stars table

Revision ID: b41adafe8fa3
Revises: 4412dcf61916
Create Date: 2026-04-23 00:37:06.965738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b41adafe8fa3'
down_revision: Union[str, Sequence[str], None] = '4412dcf61916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('constellation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fun_facts', sa.String(), nullable=True),
    sa.Column('distance_light_years', sa.Float(), nullable=True),
    sa.Column('star_type', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('right_ascension', sa.String(), nullable=True),
    sa.Column('african_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cultural_significance', sa.Text(), nullable=True),
    sa.Column('traditional_uses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seasonal_associations', sa.Text(), nullable=True),
    sa.Column('mythological_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stars_id'), 'stars', ['id'], unique=False)
    op.create_index(op.f('ix_stars_name'), 'stars', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stars_name'), table_name='stars')
    op.drop_index(op.f('ix_stars_id'), table_name='stars')
    op.drop_table('stars')
    # ### end Alembic commands ###
